### PR TITLE
mPFC glutamatergic burst analysis 45ms parameter

### PR DESCRIPTION
**Pull request by rami-hamati**

### CODE REVIEW

**Comment by nno** [comment]
Greetings, thanks for the PR. I would be happy to also support the 45 ms value as you proposed. However, another user is already using the GLU option with 16 ms, so I'd rather keep that option. How about keeping them both, for example calling them GLU-16 and GLU-45?

**Comment by ramroomh** [comment]
Thanks nno. I've added those parameters with the suggested name changes.

**Comment by nno** [comment]
@ramroomh Thanks for the update.
- did you try your own update? In Settings.java I see `GLU16_maxburststart`, I would expect `GLU-16_maxburststart`. And similar to the other keys there. 
- It seems you added `.class files`, why? Was this by accident, since you did add `java/burstiDAtor/*.class` to `.gitignore`?

**Comment by rami-hamati** [comment]
Pleasure, thanks for creating this useful tool in the first place.

**Pull request merged**
